
import DAO.ProductDAO;
import DTO.Product;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class SalesForm extends javax.swing.JFrame {
    private JComboBox<String> cboProducts;
    private JTextField txtQuantity;
    private JLabel lblPrice, lblTotal;
    private JButton btnSell;

    public SalesForm() {
        initUpdateComponents();
        loadProducts();
    }
    
    private void initUpdateComponents(){
        setTitle("Ban hang");
        setSize(400,300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(6,2,10,10));
        
        add(new JLabel("Chon San Pham:"));
        cboProducts = new JComboBox<>();
        add(cboProducts);
        
        add(new JLabel("So luong ban: "));
        txtQuantity = new JTextField();
        add(txtQuantity);
        
        add(new JLabel("Gia ban (1 SP): "));
        lblPrice = new JLabel("-");
        add(lblPrice);
        
        add(new JLabel("Thanh tien: "));
        lblTotal = new JLabel("-");
        add(lblTotal);
        
        btnSell = new JButton("ban hang");
        add(new JLabel());
        add(btnSell);
        
        cboProducts.addActionListener(e -> updatePrice());
        txtQuantity.addActionListener(e -> updateTotal());
        btnSell.addActionListener(e -> handleSell());
    }
    
    private void loadProducts(){
        List<Product> list = ProductDAO.getAllProducts();
        for(Product p : list){
            cboProducts.addItem(p.getId() + " - " + p.getName());
        }
        updatePrice();
    }
    
    private void updatePrice(){
        try {
            String selected = (String) cboProducts.getSelectedItem();
            int productId = Integer.parseInt(selected.split(" - ")[0]);
            Product p = ProductDAO.findProductById((productId));
            lblPrice.setText(String.valueOf(p.getSellPrice()));
            updateTotal();
        } catch (Exception e) {
            lblPrice.setText("-");
        }
    }
    
    private void updateTotal(){
        try {
            int qty = Integer.parseInt(txtQuantity.getText());
            double price = Double.parseDouble(lblPrice.getText());
            lblTotal.setText(String.valueOf(qty * price));
        } catch (Exception e) {
            lblTotal.setText("-");
        }
    }
    
    private void handleSell(){
        try {
            String selected = (String)cboProducts.getSelectedItem();
            int productId = Integer.parseInt(selected.split(" - ")[0]);
            int qty = Integer.parseInt(txtQuantity.getText());
            
            // check stoack & subtract (ProductDAO logic needed)
            if(ProductDAO.sellProduct(productId, qty)){
                JOptionPane.showMessageDialog(this, "Ban hang thanh cong!");
                txtQuantity.setText("");
                lblTotal.setText("-");
            } else {
                JOptionPane.showMessageDialog(this, "Ban hang that bai. Co the khong du hang ton kho");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
